### ISSUE TITLE
Alter model attributes before running create()

### ISSUE THREAD

**Issue by donpinkus** [FineLinePrototyping/angularjs-rails-resource#147]
I have a model called "action". 

```
Action
user_id:integer  name:string  configuration:text
```

The "configuration" attribute is JSON. In my Angular app, I let people set particular attributes of the JSON using inputs:

```
<input type="text" ng-model="action.configuration.subject"></input>
<input type="text" ng-model="action.configuration.message"></input>
```

Before I do `scope.action.create()` I need to make sure `configuration` is JSON.

```
scope.action.configuration = JSON.stringify(scope.action.configuration); 
```

Is there a way to automatically do JSON.stringify on a particular attribute before saving to db? (And I guess do JSON.parse() on this attribute anytime it is retrieved from the db)

**Comment by tpodom** [comment]
You could write a custom serializer function that would call stringify automatically when any serialization occurs.  Take a look at the serializeWith.
