### ISSUE TITLE
Custom RailsResource method

### ISSUE THREAD

**Issue by markalanevans** [FineLinePrototyping/angularjs-rails-resource#150]
I want to add a custom method byPlatformId to my RailsResource class.

ex:

```coffee

angular.module("sg.models").factory  "UserRetargetingPlatform", [ 'RailsResource','modelSettings', ( RailsResource, modelSettings ) ->
  class UserRetargetingPlatform extends RailsResource
    @configure url: modelSettings.api + '/user_retargeting_platforms', name: "user_retargeting_platforms"

    @byPlatformId: ( data ) ->
      url = "platform/{{platform_id}}"
      return @get(url, data)

]
```

In your docs for "Resource Urls" here 
https://github.com/FineLinePrototyping/angularjs-rails-resource#resource-urls

You have this example:

```coffee
AngularJS expression - An expression url is evaluated at run time based on the given context for non-instance methods or the instance itself. For example, given the url expression: /stores/{{storeId}}/items/{{id}}
```

As you can see, i try 

```coffee
url = "platform/{{platform_id}}"
```

but the "magic" doesn't happen and I end up with a nasty url w/ encoded curly brackets.

How do you suggest I do what i'm asking?

**Comment by tpodom** [comment]
The methods that take a custom url don't do any processing of the url.  You would need to build the url before passing it to the get method.
