### ISSUE TITLE
How to extend @configure.serializer?

### ISSUE THREAD

**Issue by uberspeck** [FineLinePrototyping/angularjs-rails-resource#153]
Our requirements are asking for our show/edit views to be one in the same so that a user may toggle between a "unlocked" (editable) and "locked" state. I've tried the following approach, but it seems the serializer in the ```BaseResource``` is being ignored. Am I taking the wrong approach?

```javascript
class BaseResource extends RailsResource
    @configure
        serializer: railsSerializer( ->
            @exclude( "$locked", "$snapshots" )
        )
   unlock: ->
        @snapshot()
        @$locked = false
   lock: ->
        @rollback()
        @$locked = true
```
```javascript
class User extends BaseResource
    @configure
        url: "/manage/users"
        name: "user"
        serializer: railsSerializer( ->
            @exclude( "$selected" )
        )
```

**Comment by tpodom** [comment]
The serializer of User would overwrite the base one.  It's an interesting scenario I've not real thought about so I don't have any immediate suggestions.
