### ISSUE TITLE
input[type="date"] throwing [ngModel:datefmt] Expected `1978-03-20` to be a date

### ISSUE THREAD

**Issue by jancel** [FineLinePrototyping/angularjs-rails-resource#154]
Are there any suggestions to handling Date types using this library or is this something we handle custom in serialization?  Trying to get the persistence working without muddying the waters a little and running into blocks with these input types.

**Comment by tpodom** [comment]
Hi, we use custom serializers for date & date time and then use <code>serializeWith('field', 'dateSerializer)</code>.

Here's our dateSerializer:
```javascript
factory('dateSerializer', function (DateTimeUtilities) {
    function DateSerializer() {
    }
    DateSerializer.prototype.serialize = function (value) {
        return value;
    };
    DateSerializer.prototype.deserialize = function (jsonDate) {
        if (angular.isDate(jsonDate)) {
            return jsonDate;
        }
        return DateTimeUtilities.getLocalDate(jsonDate);
    };
    return DateSerializer;
});
```

**Comment by jancel** [comment]
Perfect!

**Comment by ulitiy** [comment]
Are there any api changes in this case? It doesn't seem to work
