### ISSUE TITLE
How to deserialize JSON to new Date?

### ISSUE THREAD

**Issue by ulitiy** [FineLinePrototyping/angularjs-rails-resource#156]
Thanks for your gem!

I want to make the serializer to create date object from date fields when returned from the server, but serializer doesn't seem to help.

How can I convert `created_at` to `new Date(created_at)`?

Am I missing something? Seems serializer only works to convert to JSON, but not to js?

**Comment by ulitiy** [comment]
ok, let's use interceptors. But afterResponse interceptor is called with array/instance result, maybe it would be better to add separate interceptors for different types of queries?

**Comment by ulitiy** [comment]
Solution (temporary i hope)
```
  class CertificateStatus extends RailsResource
    @configure 
      url: "/certificate_statuses",
      name: "certificate_status",
      interceptors: [
        afterResponse: (result)->
          if angular.isArray result
            angular.forEach result, (item)->
              item.prepare()
          else
            item.prepare()
      ]
    prepare: ->
      @created_at = new Date(@created_at)
      this
```

**Comment by tpodom** [comment]
Check out the answer to #154.  Instead of the DateTimeUtilities which is a separate utility class it was using you can use new Date.

**Comment by ulitiy** [comment]
Great, thanks!
