### ISSUE TITLE
Circural dependency problem for models relating with belongs_to and has_many

### ISSUE THREAD

**Issue by mareczek** [FineLinePrototyping/angularjs-rails-resource#158]
Angular detects a circular dependency problem when having a simple setup of two models:

In the backend app:
```ruby
class AppointmentKindTemplate < BaseAppointmentKind
  belongs_to :medical_major
end

class MedicalMajor < ActiveRecord::Base
  has_many :appointment_kind_templates, dependent: :restrict_with_error
end
```

in the frontend app:
```coffeescript
'use strict'
angular.module('drug.services').factory 'AppointmentKindTemplate', (BaseResource, MedicalMajor, railsSerializer) ->
  class AppointmentKindTemplate extends BaseResource
    @configure
      url: '/appointment_kind_templates',
      name: 'appointment_kind_template'
      serializer: railsSerializer ->
        @resource('medicalMajor', 'MedicalMajor')

'use strict'
angular.module('drug.services').factory 'MedicalMajor', (BaseResource, AppointmentKindTemplate, railsSerializer) ->
  class MedicalMajor extends BaseResource
    @configure
      url: '/medical_majors',
      name: 'medical_major'
      serializer: railsSerializer ->
        @resource('appointmentKindTemplates', 'AppointmentKindTemplate')
```

Is it me doing something wrong or should this simply work as expected?

**Comment by tpodom** [comment]
You need to exclude one of the models from serialization from the other.

**Comment by mareczek** [comment]
Actually the defined resources are not the problem, the injector is the problem:
```coffeescript
 angular.module('drug.services').factory 'MedicalMajor', (BaseResource, AppointmentKindTemplate, railsSerializer) ->
```
and
```coffeescript
 angular.module('drug.services').factory 'AppointmentKindTemplate', (BaseResource, MedicalMajor, railsSerializer) ->
```

The setup I would like to achieve is natural and there is nothing wrong with it - i think. It seems to be the problem with angulars injector, not the serializer itself. I'm sure I'm not the first one who want's to be able to use relations. I was hoping someone found a solution.

@tpodom thanks for the suggestion, but goal is to have such a setup and fix the injector problem :-)

**Comment by tpodom** [comment]
In a case like this you may need to fetch the model service at runtime if both sides need access to the other.

**Comment by mareczek** [comment]
Your suggestion sounds promising! How does one do that? Thanks in advance

**Comment by tpodom** [comment]
You can inject the $injector service (https://docs.angularjs.org/api/auto/service/$injector <https://docs.angularjs.org/api/auto/service/$injector>) and call $injector.get(‘ModelName’).

**Comment by mareczek** [comment]
@tpodom thanks for the suggestion. If I understood correctly I implemented it as:
```coffeescript
angular.module('drug.services').factory 'MedicalMajor', ($injector, BaseResource, railsSerializer) ->
  $injector.get('AppointmentKindTemplate')

  class MedicalMajor extends BaseResource
    @configure
      url: '/medical_majors',
      name: 'medical_major'
      serializer: railsSerializer ->
        @resource('appointmentKindTemplates', 'AppointmentKindTemplate')
```
Unfortunately this also resolves in a `[$injector:cdep]`

**Comment by tpodom** [comment]
I meant you would use that in the methods that you are trying to access the AppointmentKindTemplate model.  If you’re not trying to access it directly in any methods inside MedicalMajor you don’t need to inject it at all.
