### ISSUE TITLE
How do we catch Rails validation errors?

### ISSUE THREAD

**Issue by donpinkus** [FineLinePrototyping/angularjs-rails-resource#159]
When I do `myModel.create()`, on the Rails side I have model validations.  When myModel fails the validations, Rails sets a failed status on the ajax request, in your browser's console you will see `POST http://localhost:3000/mymodels 422 (Unprocessable Entity)`. Usually I've used onError callbacks in other libraries when an XHR fails. 

What method should be used to catch errors or failed HTTP posts/puts/deletes with angularjs-rails-resource?

**Comment by tpodom** [comment]
All of the methods return promises as defined by the AngularJS documentation (https://docs.angularjs.org/api/ng/service/$q <https://docs.angularjs.org/api/ng/service/$q>).  The then method accepts a failure callback that you can register.  There’s also a catch method if you just want to catch errors an not worry about the success case.

**Comment by seanfcarroll** [comment]
Should this be closed?
