### ISSUE TITLE
Initializing resource from server side

### ISSUE THREAD

**Issue by shine60vn** [FineLinePrototyping/angularjs-rails-resource#160]
Hi guys,
I used [inherited_resources](https://github.com/josevalim/inherited_resources) for my rest api controllers and resources method in `routes.rb`. There is a API like this:
```
GET        /api/resource/new
```
I want to use this API to initialize my resource from server side (many logics need to be solved) but I didn't see any class method of RailsResource that can interact with that API. Is there any way to work around?

Thanks!

**Comment by nikolai-b** [comment]
If you create a `MyResource` class
```coffeescript
class MyResource extends RailsResource
    @configure
        url: "/manage/facilities/1/residents"
        name: 'my_resource'
```
and then you can initialize it in the controller:
```coffeescript
MyResource.$get(MyResource.$url() + '/new').then (response) ->
  $scope.resource = response
```

**Comment by shine60vn** [comment]
Ok, got it. I will close this issue. Thank you!
