### ISSUE TITLE
How to use different base url in dev/production?

### ISSUE THREAD

**Issue by uberspeck** [FineLinePrototyping/angularjs-rails-resource#161]
In production my app will make resource requests to an api like ```api.myapp.com``` and in dev the requests will be more like ```localhost:8088```. Is there a mechanism for setting a base url for requests?

**Comment by uberspeck** [comment]
I'll just try a generic approach for now...

```coffeescript
angular
  .module( "app.services" )
  .service( "api", ($location) ->
    if (/localhost/).test( $location.host() )
      "baseUrl": "http://localhost:3001"
    else
      "baseUrl": "http://api.myapp.com/v2/"
  )
  .config( ($httpProvider) ->
    $httpProvider.interceptors.push( ($q, api) ->
      "request": (config) ->
        config.url = config.url.replace(/^\/api/, api.baseUrl)
        config || $q.when(config)
    )
  )
```

**Comment by ClydeDroid** [comment]
This is actually super helpful and should be included in the documentation. I don't think the package should assume that the backend resides on the same host.
