### ISSUE TITLE
underscoreParams(false) still sending underscore

### ISSUE THREAD

**Issue by uberspeck** [FineLinePrototyping/angularjs-rails-resource#162]
I've set ```underscoreParams``` to false, but my requests are still being converted from camelCase to underscore. What am I missing?

```coffeescript
angular
  .module( "app" )
  .config( (RailsResourceProvider) ->
    RailsResourceProvider
      .rootWrapping(false)
      .underscoreParams(false)
  )
```

**Comment by tpodom** [comment]
When you say your requests are being converted to underscore are you referring to the query parameters (what underscoreParams affects) or the data (controlled by serializer underscore function)?  If you’re trying to disable underscore for the data on all requests you can inject the railsSerializerProvider and set the underscore function.  This is the example from the docs on disabling underscore:

angular.module('app').config(["railsSerializerProvider", function(railsSerializerProvider) {
    railsSerializerProvider.underscore(angular.identity).camelize(angular.identity);
}]);

**Comment by uberspeck** [comment]
Thanks @tpodom, that's exactly what I was looking for. I completely misread the docs and got myself confused re: RailsResourceProvider/railsSerializerProvider
