### ISSUE TITLE
$post modifies the receiver

### ISSUE THREAD

**Issue by nicooga** [FineLinePrototyping/angularjs-rails-resource#165]
I'll go directly to the point. `$post` modifies the receiver on success as opposed to what docs say that it should do. I think the problem is here:

https://github.com/FineLinePrototyping/angularjs-rails-resource/blob/923a065cefad728320c122a78e6d865abb523e90/vendor/assets/javascripts/angularjs/rails/resource/resource.js#L729

`this` is being passed as context for the HTTP call handler, an therefore modifying the receiver. I found this problem trying to use $post on an object Order which has many items. After the `$post` call succeeded, `order.items` was set to `[]`.

As a proof that this is the problem I redefined `$post` on my resource like this:

~~~javascript
Order.prototype.$post = function (url) {
  var data = angular.copy(this, {});

  var httpConfig = angular.extend({
    method: 'POST',
    url:    url,
    data:   data
  }, this.constructor.getHttpConfig());

  return this.constructor.$http(httpConfig, null);
}
~~~
.. which removed the issue completely.

**Comment by tpodom** [comment]
The prototype $post is intended to operate on the instance itself.  The intent of the method is to allow you to post it to a custom url.  If you don't want it to modify the instance then you should use the class level $post method <code>Order.$post</code>.
