### ISSUE TITLE
Converting undefined to null

### ISSUE THREAD

**Issue by palodelincak** [FineLinePrototyping/angularjs-rails-resource#167]
Right now, when attribute has `undefined` value, this attribute is removed and is not send in params.

I would like to ask you, if it is possible to convert `undefined` values to `null` values?

I wrote interceptor, but I'm not sure if this is the right way how to do this... Also - is there some way how to use this interceptor as global? So there is no need to add it to each model?

```
angular.module('rails').factory('sanitizeUndefinedAttributeValueInterceptor', function () {
  return {
    'beforeRequest': function (httpConfig) {
      if ((httpConfig.method === 'post' || httpConfig.method === 'put') && httpConfig.data) {
        _.each(httpConfig.data, function(value, key) {
          if (value === undefined) httpConfig.data[key] = null;
        });
      }
      return httpConfig;
    }
  };
});
```

**Comment by tpodom** [comment]
One way to accomplish that across all resources is to write it as an extension and configure that in the global config (https://github.com/FineLinePrototyping/angularjs-rails-resource#mixins).  The snapshots extension we use in that way and inside the extension you can register an beforeRequest interceptor doing exactly what you have.
