### ISSUE TITLE
npm install angularjs-rails-resource

### ISSUE THREAD

**Issue by joselo** [FineLinePrototyping/angularjs-rails-resource#168]
Is there any way to install this package using

npm install angularjs-rails-resource

I get an error, even if I try with:

npm install https://github.com/FineLinePrototyping/angularjs-rails-resource --save

Connection time out

Any idea?

**Comment by tpodom** [comment]
I'm not sure. We did some work to get it working now with bower but I don't think I've tried using npm to install it.

**Comment by joselo** [comment]
Thanks for your quick answer,

Actually I just try with:

npm install FineLinePrototyping/angularjs-rails-resource --save

And it works perfect :)

Thanks!
