### ISSUE TITLE
Dynamic defaultParams

### ISSUE THREAD

**Issue by mrodrigues** [FineLinePrototyping/angularjs-rails-resource#170]
I have a resource that must send a parameter besides it's id on every request. Is there a way I could use the `defaultParams` to dynamically set the request's parameters? I've tried to pass a function as argument instead of a object, but it didn't evaluate.

**Comment by tpodom** [comment]
I think the easiest solution is to add a `beforeRequest` interceptor and modify the httpConfig.params object.  The `defaultParams` doesn't have any dynamic functionality.
