### ISSUE TITLE
Support for Mongoid

### ISSUE THREAD

**Issue by WagnerMatos** [FineLinePrototyping/angularjs-rails-resource#174]
I was wondering if support for different ORM is provided. The reason I'm asking is that the update method doesn't seen to work in my setup. After investigating, it seems the issue may be with the Mongoid ID is provided `model._id.$oid` that might be different than using ActiveModel.

**Comment by tpodom** [comment]
We haven't worked with mongoid so I can't speak to what would be required to make that work.

**Comment by WagnerMatos** [comment]
In fairness one could change the serialisation to accommodate that. I just changed the serialisation in [Mongoid] (http://stackoverflow.com/questions/22520393/mongodb-angularjs-id-empty-in-update-via-resourceprovider) which seemed simpler.
