### ISSUE TITLE
OPTIONS instead of GET

### ISSUE THREAD

**Issue by thiagofesta** [FineLinePrototyping/angularjs-rails-resource#175]
I have something like this:
```
    railsResourceFactory({
      url: '/books'
      name: 'book',
      pluralName: 'books'
    });
```

When I use it, instead of making a GET request `Book.query()`, it makes a OPTIONS request.

It seems to be related with the `rootWrapping`. If I set the `rootWrapping` to `false`, it works fine as a GET request. But I want to use the `rootWrapping`, and I need to.

I started looking at the code and I found this line: https://github.com/FineLinePrototyping/angularjs-rails-resource/blob/v2.0.0/vendor/assets/javascripts/angularjs/rails/resource/resource.js#L562

This one seems to be the problem. If I comment this line, it works fine, it makes a GET request and also unwrap correctly.

What is going on there? Anything am I doing wrong? maybe a bug? Why adding the data property to the request?

**Comment by tpodom** [comment]
What version of AngularJS are you using?  Perhaps there’s a new feature with $http that triggers OPTIONS to execute?

**Comment by thiagofesta** [comment]
@tpodom I am using Angular 1.2.28 and as linked I am using version angularjs-rails-resource 2.0.0.

uhmm let me think

**Comment by tpodom** [comment]
A quick google turned up this that may be related?

http://stackoverflow.com/questions/12111936/angularjs-performs-an-options-http-request-for-a-cross-origin-resource <http://stackoverflow.com/questions/12111936/angularjs-performs-an-options-http-request-for-a-cross-origin-resource>

**Comment by thiagofesta** [comment]
@tpodom not sure, it says:

> in particular, for HTTP methods other than GET, or for POST usage with certain MIME types

I made few other tests, I kept the line I mentioned before, but I removed the headers that was sent with the `$http` call. They were: 
```
headers: {
  "Accept": "application/json",
  "Content-Type": "application/json"
},
```

When I removed those headers, it worked fine, even with the data on it.

**Comment by thiagofesta** [comment]
@tpodom check this out: https://code.angularjs.org/1.2.27/docs/api/ng/service/$http

See the section called: "Setting HTTP Headers"

Angular does not send `Content-Type` for GET requests. I removed that before calling the `$http` and worked fine. The bad part about that, is that is not configurable, because it's defaults here: https://github.com/FineLinePrototyping/angularjs-rails-resource/blob/v2.0.0/vendor/assets/javascripts/angularjs/rails/resource/resource.js#L216

**Comment by thiagofesta** [comment]
@tpodom here is how I fixed this problem...

```
    RailsResourceProvider.httpConfig({
      headers: {
        'Accept': $httpProvider.defaults.headers.common['Accept'],
        'Content-Type': undefined
      }
    });
```
