### ISSUE TITLE
JSON API compatible?

### ISSUE THREAD

**Issue by uberspeck** [FineLinePrototyping/angularjs-rails-resource#179]
Is it possible to work with the [JSON API](http://jsonapi.org) format in angular-rails-resource?

**Comment by garysweaver** [comment]
Nope. Rails way of doing REST-ish JSON APIs is not the same.

If it is a real need, check out the stuff on http://jsonapi.org/implementations/ - e.g. https://github.com/jakubrohleder/angular-jsonapi
