### ISSUE TITLE
Turn off underscores for camelCase for the pluralName

### ISSUE THREAD

**Issue by thiagofesta** [FineLinePrototyping/angularjs-rails-resource#180]
For attributes it works: https://github.com/FineLinePrototyping/angularjs-rails-resource#i-like-underscores-how-can-i-turn-off-the-name-conversion

but for pluralName like: 'workExperience', it always converts to work_experience.

But on my API it is camelcase, so it does not work.

**Comment by tpodom** [comment]
I'm not sure why that would be, we use the serializer underscore method for doing the conversion:

```javascript
this.config.pluralName = this.config.serializer.underscore(cfg.pluralName || this.config.serializer.pluralize(this.config.name));
```

**Comment by thiagofesta** [comment]
I am not sure why, but I added some console.log on the wrap method.

```result[angular.isArray(data) ? resource.config.pluralName : resource.config.name] = data;```

Seems like at this time it is not configured yet.

**Comment by tpodom** [comment]
I just wrote a test with Plunker and the plural name was not underscored.

http://plnkr.co/edit/8clumSi6ZF1q8TLxqTtn?p=preview

**Comment by thiagofesta** [comment]
http://plnkr.co/edit/318EL8QWXh3YGFFeEXzs?p=preview
http://plnkr.co/edit/GDBurn0l7AM9ZANv0Lts?p=preview

Confirmed! It was my issue, I was adding the config on the wrong module, which was causing issues.
Both Plunker that I wrote works fine.

Thank you
