### ISSUE TITLE
Access parent from a nested attribute?

### ISSUE THREAD

**Issue by mrjamesriley** [FineLinePrototyping/angularjs-rails-resource#184]
Hello! Firstly, thanks for the great library.

My question: Is it possible to access the parent of a nested resource, from the child? e.g If I have a Book resource, that has nested Pages - how do I access the Book from one of the pages?

In Rails for example, you'd expect to be able to call `page.book` from any of the children - and thanks to the Rails associations, get the Book that the Page `belongs_to`. Is there a built in method to be able to navigate up to the parents?

At the moment, I'm having to iterate over every Book for example, and check each of it's `book.pages`, looking for the page that matches the page I'm working with, in order to then return the Book - which feels cumbersome, particularly when working with a Resource that has two levels of nested attributes.

Am I overlooking anything?

**Comment by tpodom** [comment]
Well there's nothing currently built-in that will provide that for you.  You could write an ```afterResponse``` interceptor on ```Book``` that iterates through its pages that sets a reference of book on each ```Page```.

**Comment by mrjamesriley** [comment]
Really appreciate the prompt response.
Have gone with an `afterResponse` as recommend, works a treat.

cheers
