### ISSUE TITLE
Custom deserialization

### ISSUE THREAD

**Issue by jnfeinstein** [FineLinePrototyping/angularjs-rails-resource#185]
I'm using an object that has a timestamp.  We're using [momentjs](http://momentjs.com/) to manipulate timestamps, which requires doing essentially `this.createdAt = moment(this.createdAt)`.  I am currently doing this in an `afterResponse` interceptor, which works fine.  However the snapshot mixin serializes the values and then restores the raw values during `rollback()`.

Is there a recommended method for this?

**Comment by tpodom** [comment]
Sorry, missed this over this holidays.  We do something similar for dates but use a serializer to handle the serialization:

```javascript
angular.module('book.serializers').factory('dateSerializer', function (moment) {
    function DateSerializer() {
    }

    DateSerializer.prototype.serialize = function (value) {
        return value;
    };

    DateSerializer.prototype.deserialize = function (jsonDate) {
        if (angular.isDate(jsonDate)) {
            return jsonDate;
        }
        return moment(jsonDate);
    };
    return DateSerializer;
});

angular.module('book.services').factory('Book', ['railsResourceFactory', function (railsResourceFactory) {
    var resource = railsResourceFactory({
      url: '/books', 
      name: 'book',
      serializer: railsSerializer(function () {
          this.serializeWith('expirationDate', 'dateSerializer');
      })
    });
}]);
```
