### ISSUE TITLE
How to properly extend constructor

### ISSUE THREAD

**Issue by nicooga** [FineLinePrototyping/angularjs-rails-resource#186]
Hi there. I'm trying to extend the constructor to do some things when the resource is initialized.
More specifically, just for background, I wan't to bind a websocket listener to update the "instance" every now and then.

I've started with this Student "class" that works:

~~~javascript
(function() {
  "use strict";

  angular
    .module("app")
    .factory("Student", factoryConstructor);

  function factoryConstructor(railsResourceFactory) {
    return railsResourceFactory({
      url: '/api/students',
      name: 'student',
      serializer: railsSerializer(function() {
        this.nestedAttribute("phoneNumber")
      })
    });
})();
~~~

That's fine. Then I followed the little guide at the extension section of the README.

~~~javascript
(function() {
  "use strict";

  angular
    .module("app")
    .factory("Student", factoryConstructor);

  function factoryConstructor(RailsResource, railsSerializer, EventDispatcher) {
    function Student() {
      RailsResource.constructor.apply(this, arguments)
    };

    RailsResource.extendTo(Student);

    Student.configure({
      url: '/api/students',
      name: 'student',
      serializer: railsSerializer(function() {
        this.nestedAttribute("phoneNumber")
      })
    });

    return Student;
  }
})();
~~~
That's fine, kind of. But there are 2 things that I do not understand. First, the docs say you should call  `RailsResource.__super__.constructor.apply(this, arguments)` but `RailsResource.__super__` is not defined, so I used `RailsResource.constructor` instead. I don't think thats OK.

And second, If I put a debugger here:

~~~javascript
    function Student() {
      RailsResource.constructor.apply(this, arguments)
      debugger
    };
~~~
... `this` is undefined and `arguments` is empty, when I called `Student.get(id).then(...)`. I got stuck here. I need to put something like this in the constructor:

~~~javascript
    function Student() {
      RailsResource.constructor.apply(this, arguments)
      EventDispatcher.channel("students_" + this.id).
        bind("updated", function (student) {
          angular.extend(this, student);
        });
    };
~~~

What have I missed? BTW, great library!

**Comment by nicooga** [comment]
OK, I find out I'm dumb and I should used `Student.__super__` which is set by `RailsResource.extendTo`, and is the same as `RailsResource.constructor` (?).

Anyway, `this` and `arguments` are still missing when the constructor is called. I'm scratching my head, maybe `Student.get` was implemented something like:

~~~javascript
var obj = new Student;
angular.extend(obj, dataFromAjax);
~~~
... which will make my attemps to extend the constructor useless.

**Comment by tpodom** [comment]
The constructor is not passed the response data.  In the case of a <code>get</code> we construct the object and then copy in the values one-by-one as they are deserialized.  You can accomplish what you want using an afterResponse interceptor (see below).  That will also handle the scenario of the result of an <code>update</code> response.

```javascript
Student.prototype.dispatchUpdate = function() {
  EventDispatcher.channel("students_" + this.id).
        bind("updated", function (student) {
          angular.extend(this, student);
        });
}

Student.interceptAfterResponse(function (result) {
  if (angular.isArray(result)) {
    angular.forEach(result, function (resource) {
      resource.dispatchUpdate();
    });
  } else {
    result.dispatchUpdate();
  }
});
```
