### ISSUE TITLE
How to send request to a custom route?

### ISSUE THREAD

**Issue by vhilly** [FineLinePrototyping/angularjs-rails-resource#188]
Let's say I have the following rails route..

resources :members do
  member do 
    get 'approve_membership'
  end
end

how do I send request to  'members/1234/approve_membership' ?

**Comment by tpodom** [comment]
I would add a custom function on the prototype of the resource that returns this.$url(''approve_membership')

**Comment by vhilly** [comment]
Hi,

Thanks for quick reply. Can you give me a sample?

Thanks in advance

**Comment by tpodom** [comment]
```javascript
angular.module('book.services').factory('Book', ['railsResourceFactory', 'Author', function (railsResourceFactory, Author) {
    var resource = railsResourceFactory({url: '/books', name: 'book'});
    resource.prototype.getAuthor = function () {
        return this.$url('author');
    };
    return resource;
}]);
```
