### ISSUE TITLE
3 levels of nesting

### ISSUE THREAD

**Issue by valeksiev** [FineLinePrototyping/angularjs-rails-resource#190]
Hi,

I have the following example:

Resources:

```
class Campaign extends RailsResource
    @configure({
     ...
      serializer: railsSerializer(() ->
        this.resource('emails')
        this.nestedAttribute('emails')
      )
    })

 class Email extends RailsResource
    @configure({
    ...
      serializer: railsSerializer(() ->
        this.resource('emailTemplate')
        this.nestedAttribute('emailTemplate')
      )
    ...
    })

class EmailTemplate extends RailsResource
    @configure({
     ...
    })
```

Controller:

```
$scope.campaign = new Campaign(
  emails: [
    new Email(
      emailTemplate: new EmailTemplate(
        html: 'some html...'
      )
    )
  ]
)
$scope.campaign.save().then((response) ->
  console.log response
)

```

When I get the request params on the backend they have the following structure:

```
{
  "campaign" => {
    "emails_attributes" => [
      "email_template" => {
        "html" => "some html .."
      }
    ]
  }
}
```
while I expect
```
{
  "campaign" => {
    "emails_attributes" => [
      "email_template_attributes" => {
        "html" => "some html .."
      }
    ]
  }
}
```
The `email_template` key should be called `email_template_attributes` otherwise the `accepts_nested_attributes_for` in the Rails models won't work.

Is there something I am missing or the 3 level resource nesting is not supported?

**Comment by tpodom** [comment]
This seems like a bug. I don't see anything obviously wrong with your example.

**Comment by tpodom** [comment]
I figured out what was wrong with your example.  The call <code>this.resource('emailTemplate')</code> should be <code>this.resource('emailTemplate', 'EmailTemplate')</code>.
