### ISSUE TITLE
this.constructor.deserialize is not a function

### ISSUE THREAD

**Issue by GCorbel** [FineLinePrototyping/angularjs-rails-resource#192]
Hello,

I'm using this factory : 

@t4bApp.factory('Order', ['RailsResource', (RailsResource) ->
  class Order extends RailsResource
    url: '/account/orders',
    name: 'order'
])

like this : `Order(@order).create()`.

And I have this error : 

    Error: this.constructor.deserialize is not a function

It break at [this like](https://github.com/FineLinePrototyping/angularjs-rails-resource/blob/master/vendor/assets/javascripts/angularjs/rails/resource/resource.js#L116). I'm using Angular 1.5.0.

**Comment by tpodom** [comment]
Shouldn't it be ```new Order(@order).create()```?

**Comment by GCorbel** [comment]
Oups, you're right... Thanks!
