### ISSUE TITLE
Specifying custom paths for updates not updating original object

### ISSUE THREAD

**Issue by ryancrisp** [FineLinePrototyping/angularjs-rails-resource#205]
I have a resource which I'm trying to specify some additional custom patch URLs.  I can create these on the resource, but the issue is that it doesn't update the original resource like the `update()` or `save()` methods do, which I expected it to do.  Is this a bug or am I responsible for doing this, and if so, what's the best way to go about it? 

Here is an example resource:

```
    var resource = railsResourceFactory({
        url: '/api/projects',
        name: 'project'
    });

    resource.prototype.submit       = function() { return resource.$patch(this.$url('submit'), this); };
    resource.prototype.approve      = function() { return resource.$patch(this.$url('approve'), this); };

    return resource;
```

**Comment by tpodom** [comment]
You should be able to use this.$patch and it work as you expected.

**Comment by ryancrisp** [comment]
Ah, of course, that makes sense!  I can confirm that works as I expected.  Thank you very much for the quick response.
