### ISSUE TITLE
New "Possibly unhandled rejection" on angular 1.6

### ISSUE THREAD

**Issue by odedniv** [FineLinePrototyping/angularjs-rails-resource#207]
Angular 1.6 now sends unhandled rejections of `$q` (including `$http`'s) to `$exceptionHandler`.

If you know a rejection might occur, you're supposed to add a `.catch(function)` to your promise, which prevents an error being sent to `$exceptionHandler`.

For some reason angularjs-rails-resource's wrapping around the `$http` call prevents it, even though I added a catch it still shows the error. Using raw `$http` works as expected.

Example:

```javascript
// This doesn't throw the error when server returns 404.
$http.get("/api/session").catch(function (response) { });
// This does throw an error
Session.get().catch(function (response) { });
```

For anyone getting here for a workaround: https://docs.angularjs.org/api/ng/provider/$qProvider

**Comment by tpodom** [comment]
@odedniv Sorry for the slow response.  I wrote a test case now that our tests are running against Angular 1.6 and I wasn't able to reproduce this.  If I remove the catch I get the possibly unhandled rejection error but with the catch it works.  Maybe it only happens when the resource is configured a certain way?  Could you provide the details for how Session resource is defined?

Here's my unit test:
```javascript
        it('get should catch exceptions on failure', function () {
            inject(function ($exceptionHandler) {
                var failure = false;

                $httpBackend.expectGET('/test/123').respond(500);

                Test.get(123).catch(function (response) { failure = true});

                $httpBackend.flush();
                expect($exceptionHandler.errors).toEqual([]);
                expect(failure).toBeTruthy();
            });
        });
```

**Comment by odedniv** [comment]
Got it: https://github.com/jmdobry/angular-cache/issues/259

It's a problem with `CacheFactory`, you can try adding this to your `RailsResource` to reproduce:

```javascript
httpConfig: { cache: { CacheFactory('default') } }
```

Thanks for the help, will add a gift README pull request for using this library with `npm` :)
