### ISSUE TITLE
$snapshots is persisted to server in Angular 1.3+

### ISSUE THREAD

**Issue by joel-nyansa** [FineLinePrototyping/angularjs-rails-resource#209]
Angular 1.3 changed `toJson` to strip all fields beginning with `$$` instead of just `$` ([commit](https://github.com/angular/angular.js/commit/c054288c9722875e3595e6e6162193e0fb67a251)).  The snapshot extension is using `$snapshots` which is being serialized and saved in later versions of Angular.  Your test suite is hard coded to use Angular 1.2.6 which is presumably also an issue.

The easiest fix would be to rename `$snapshots` to `$$snapshots` and require Angular 1.3+.  Happy to do this if it is agreed that this is the best approach.

**Comment by tpodom** [comment]
That approach sounds ok to me.  Thanks!

**Comment by jnfeinstein** [comment]
@tpodom opened PR #210 to close this issue.
