### ISSUE TITLE
Response `headers()` doesn't return correct headers

### ISSUE THREAD

**Issue by nicooga** [FineLinePrototyping/angularjs-rails-resource#211]
I have a model like this:

~~~js
  User.configure({
    url:  'http://localhost:3000/v1/users',
    name: 'user',
    serializer: railsSerializer(function() {
      this.serializeWith('startsAt', 'DateSerializer');
      this.serializeWith('endsAt', 'DateSerializer');

      this.nestedAttribute('taughtSubjects');
      this.nestedAttribute('location');
      this.nestedAttribute('availabilityPeriods');
    }),
    fullResponse: true  // I've tried this, to get the headers
  });

  // I've also tried this
  User.interceptResponse((response, constructor, context) => {
    response.data.totalPages = response.headers('Total');
    console.log(response.headers('Total'))
    console.log(response.headers())
    return response;
  });
~~~

I any case `response.headers()` returns `Object {content-type: "application/json", cache-control: "max-age=0, private, must-revalidate"}`, although I can see in the network tab there are a bunch of other headers, like for example, `Total` and `Per-Page`, which are the ones I'm interested on.

No luck when asking for an specific header either (`response.headers('Total')`)

**Comment by tpodom** [comment]
@nicooga I'm not sure why that wouldn't be working for you.  We don't do any processing of the response headers.  Does it work if you use $http?

**Comment by nicooga** [comment]
It had to do with CORS. I didn't know I had to especify the ´Access-Control-Expose-Headers´. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers. Silly me. Thanks for the response anyways.
